# Build customization
build:
  # Path to main.go file.
  # Default is `main.go`
  main: ./p3y.go
  binary: p3y

  env:
    - CGO_ENABLED=0

  # GOOS list to build in.
  # For more info refer to https://golang.org/doc/install/source#environment
  # Defaults are darwin and linux
  goos:
    - linux
    - darwin
    - arm
    - windows

  # GOARCH to build in.
  # For more info refer to https://golang.org/doc/install/source#environment
  # Defaults are 386 and amd64
  goarch:
    - amd64
    - arm

  ldflags: -s -w -X main.Version={{.Version}}

release:
  # Repo in which the release will be created.
  # Default is extracted from the origin remote URL.
  github:
    owner: txn2
    name: p3y

  # If set to true, will not auto-publish the release.
  # Default is false.
  draft: false

  # If set to true, will mark the release as not ready for production.
  # Default is false.
  prerelease: false

  # You can change the name of the GitHub release.
  # Default is ``
  name_template: "{{.ProjectName}}-v{{.Version}} {{.Env.USER}}"

  # You can disable this pipe in order to not upload any artifacts to
  # GitHub.
  # Defaults to false.
  disable: false

nfpm:
  name_template: '{{ .ProjectName }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  homepage:  https://github.com/txn2/p37
  description: Mini reverse proxy with Basic Auth and TLS support.
  maintainer: Craig Johnston <cjimti@gmail.com>
  license: Apache 2.0
  vendor: TXN2
  formats:
    - deb
    - rpm
  recommends:
    - rpm

# Archive customization
archive:
  # You can change the name of the archive.
  # This is parsed with Golang template engine and the following variables.
  name_template: "{{.ProjectName}}_{{.Os}}_{{.Arch}}"

  # Archive format. Valid options are `tar.gz` and `zip`.
  # Default is `zip`
  format: tar.gz

  # Replacements for GOOS and GOARCH on the archive name.
  # The keys should be valid GOOS or GOARCH values followed by your custom
  # replacements.
  # By default, `replacements` replace GOOS and GOARCH values with valid outputs
  # of `uname -s` and `uname -m` respectively.
  replacements:
    amd64: amd64
    386: 386
    darwin: macOS
    linux: linux

  format_overrides:
    - goos: windows
      format: zip

  # Additional files you want to add to the archive.
  # Defaults are any files matching `LICENCE*`, `LICENSE*`,
  # `README*` and `CHANGELOG*` (case-insensitive)
  files:
    - LICENSE

brew:
  name: p3y

  github:
    owner: txn2
    name: homebrew-tap

  commit_author:
    name: Craig Johnston
    email: cjimti@gmail.com

  folder: Formula

  homepage: https://github.com/txn2/p3y

  description: "Mini reverse proxy with Basic Auth and TLS support."

  skip_upload: false

  test: |-
    kubefwd version

snapcraft:
  name_template: '{{ .ProjectName }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  summary: Mini reverse proxy with Basic Auth and TLS support.
  description: |
    Mini reverse proxy with Basic Auth and TLS support for use as a light weight
    alternative to nginx.
  replacements:
    amd64: 64-bit
    386: 32-bit
    darwin: macOS
    linux: Tux

  publish: false

  grade: stable
  confinement: classic


dockers:
  -
    goos: linux
    goarch: amd64
    goarm: ''
    binaries:
      - p3y
    dockerfile: Dockerfile
    image_templates:
      - "txn2/p3y:latest"
      - "txn2/p3y:{{ .Tag }}"
      - "txn2/p3y:v{{ .Major }}"
      - "txn2/p3y:amd64-{{ .Tag }}"
      - "txn2/p3y:amd64-v{{ .Major }}"
    build_flag_templates:
      - "--label=org.label-schema.schema-version=1.0"
      - "--label=org.label-schema.version={{.Version}}"
      - "--label=org.label-schema.name={{.ProjectName}}"
  -
    goos: linux
    goarch: arm
    goarm: 6
    binaries:
      - p3y
    dockerfile: Dockerfile
    image_templates:
      - "txn2/p3y:armv6-latest"
      - "txn2/p3y:armv6-{{ .Tag }}"
      - "txn2/p3y:armv6-v{{ .Major }}"
    build_flag_templates:
      - "--label=org.label-schema.schema-version=1.0"
      - "--label=org.label-schema.version={{.Version}}"
      - "--label=org.label-schema.name={{.ProjectName}}"